# Generated by Django 5.0.1 on 2024-01-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('aspect', models.CharField(help_text='Identify the aspect of technical debt', max_length=255)),
                ('description', models.TextField(help_text='Describe the technical debt')),
                ('metric_value', models.FloatField(help_text='Enter metric value for measurement')),
                ('impact_category', models.CharField(help_text='Categorize the impact of technical debt', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
